### ISSUE TITLE
failed to clone

### ISSUE THREAD

**Issue by lelelelelelelelelelelelele** [chunhuizhang/full_stack#1]
你好，我是b站来的，试图clone你的这个库时会出现报错，原因是
```
error: invalid path 'tutorials/python/*args_**kwargs.ipynb'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
```
'tutorials/python/*args_**kwargs.ipynb'这个路径不能被windows正确识别，包含了特殊符号，可否进行修改呢？

有一种办法可以正常clone, 输入
`git config --global core.protectNTFS false`
禁用 NTFS 的路径保护

**Comment by chunhuizhang** [comment]
ok, renamed. thanks!
